from __future__ import annotations

from typing import Protocol, runtime_checkable

from hatui.models import (
    AuditEvent,
    Computer,
    ConnectorStatus,
    Contact,
    DirectoryRole,
    DomainController,
    ForestHealth,
    FsmoRole,
    GpoLink,
    Group,
    Job,
    LicenseSku,
    Mailbox,
    MailboxPermission,
    MailboxRight,
    MailboxType,
    MailFlowConnector,
    OrgUnit,
    ReplicationPartner,
    ServiceAccount,
    Site,
    SoftDeleted,
    SyncStatus,
    Trust,
    User,
)


class NotConfiguredError(RuntimeError):
    """Raised when a live connector is used without credentials."""


class HatuiError(RuntimeError):
    pass


@runtime_checkable
class DirectoryBackend(Protocol):
    def list_users(self, query: str = "") -> list[User]: ...
    def get_user(self, user_id: str) -> User: ...
    def create_user(self, **fields: object) -> User: ...
    def set_user_enabled(self, user_id: str, enabled: bool) -> User: ...
    def unlock_user(self, user_id: str) -> User: ...
    def reset_password(self, user_id: str, temp: str, must_change: bool = True) -> User: ...
    def move_user(self, user_id: str, ou_id: str) -> User: ...
    def list_groups(self, query: str = "") -> list[Group]: ...
    def create_group(self, **fields: object) -> Group: ...
    def set_group_members(self, group_id: str, member_ids: list[str]) -> Group: ...
    def add_group_member(self, group_id: str, member_id: str) -> Group: ...
    def remove_group_member(self, group_id: str, member_id: str) -> Group: ...
    def list_computers(self, query: str = "") -> list[Computer]: ...
    def set_computer_enabled(self, computer_id: str, enabled: bool) -> Computer: ...
    def list_contacts(self, query: str = "") -> list[Contact]: ...
    def list_service_accounts(self, query: str = "") -> list[ServiceAccount]: ...
    def list_ous(self) -> list[OrgUnit]: ...
    def create_ou(self, name: str, parent_id: str | None, description: str = "") -> OrgUnit: ...
    def list_dcs(self) -> list[DomainController]: ...
    def list_fsmo(self) -> list[FsmoRole]: ...
    def list_sites(self) -> list[Site]: ...
    def list_gpos(self) -> list[GpoLink]: ...
    def set_gpo_enabled(self, gpo_id: str, enabled: bool) -> GpoLink: ...
    def list_replication(self) -> list[ReplicationPartner]: ...
    def list_trusts(self) -> list[Trust]: ...


@runtime_checkable
class MailBackend(Protocol):
    def list_mailboxes(self, query: str = "") -> list[Mailbox]: ...
    def get_mailbox(self, mailbox_id: str) -> Mailbox: ...
    def create_mailbox(
        self,
        display_name: str,
        alias: str,
        mailbox_type: MailboxType,
        user_id: str | None = None,
    ) -> Mailbox: ...
    def enable_mailbox(self, user_id: str, mailbox_type: MailboxType | None = None) -> Mailbox: ...
    def set_mailbox_forwarding(self, mailbox_id: str, smtp: str | None) -> Mailbox: ...
    def set_litigation_hold(self, mailbox_id: str, hold: bool) -> Mailbox: ...
    def set_auto_reply(self, mailbox_id: str, enabled: bool) -> Mailbox: ...
    def set_archive(self, mailbox_id: str, enabled: bool) -> Mailbox: ...
    def set_hidden(self, mailbox_id: str, hidden: bool) -> Mailbox: ...
    def list_permissions(self, mailbox_id: str | None = None) -> list[MailboxPermission]: ...
    def grant_permission(
        self,
        mailbox_id: str,
        trustee: str,
        rights: MailboxRight,
        automapping: bool = True,
        calendar_level: str | None = None,
    ) -> MailboxPermission: ...
    def revoke_permission(self, permission_id: str) -> None: ...
    def list_mail_flow(self) -> list[MailFlowConnector]: ...


@runtime_checkable
class CloudBackend(Protocol):
    def list_cloud_users(self, query: str = "") -> list[User]: ...
    def list_guests(self, query: str = "") -> list[User]: ...
    def list_licenses(self) -> list[LicenseSku]: ...
    def assign_license(self, user_id: str, sku: str) -> User: ...
    def remove_license(self, user_id: str, sku: str) -> User: ...
    def list_roles(self) -> list[DirectoryRole]: ...
    def list_soft_deleted(self) -> list[SoftDeleted]: ...
    def restore_deleted(self, object_id: str) -> User: ...


@runtime_checkable
class HybridBackend(Protocol):
    def sync_status(self) -> SyncStatus: ...
    def run_delta_sync(self) -> SyncStatus: ...
    def run_full_sync(self) -> SyncStatus: ...
    def forest_health(self) -> ForestHealth: ...
    def connector_status(self) -> list[ConnectorStatus]: ...


@runtime_checkable
class OpsBackend(Protocol):
    def list_jobs(self) -> list[Job]: ...
    def list_audit(self) -> list[AuditEvent]: ...


@runtime_checkable
class HatuiBackend(
    DirectoryBackend, MailBackend, CloudBackend, HybridBackend, OpsBackend, Protocol
):
    """Composite backend the TUI talks to."""
